
# DynamoDB config
amazon:
  dynamodb:
    region: us-east-1
    endpoint: http://localhost:8000/
  aws:
    accesskey: access_key
    secretkey: secret_key

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

kafka:
  bootstrap_address: localhost:9092
  producer:
    enabled: false
  consumer:
    enabled: false
    group_id: demo-1
    auto_offset_reset: earliest

server:
  port: 8080

services:
  ssn:
    host: http://localhost:1080