
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/webflux-demo

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

services:
  ssn:
    host: http://localhost:1080