
# DynamoDB config
amazon:
  dynamodb:
    region: us-east-1
    endpoint: http://localhost:8000/
  aws:
    accesskey: access_key
    secretkey: secret_key

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

services:
  ssn:
    host: http://localhost:1080